
server:
  adminConnectors:
    - type: http
      port: 8090
  applicationConnectors:
    - type: http
      port: 8089

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://localhost:3306/logisticsadaptor
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate.generate_statistics: false
    hibernate.show_sql: true
    hibernate.format_sql: false
    hibernate.hbm2ddl.auto: update
logging:
  level: INFO
